### ISSUE TITLE
Minimum SDK version

### ISSUE THREAD

**Issue by StelianMorariu** [SecrecySupportTeam/secrecy#115]
Could we consider increasing the minimum SDK version to 14/15 ?

![distribution](https://cloud.githubusercontent.com/assets/1908415/6651729/79eeb9a0-ca5a-11e4-9d7d-3fc62bf0d8f8.png)

**Comment by L-Henke** [comment]
What would be the advantage for us?

**Comment by StelianMorariu** [comment]
First thing is we could drop the PreferenceFragment library (if I'm not mistaken PreferneceFragment was added in api 11).

**Comment by L-Henke** [comment]
Sounds reasonable. But wouldn't it be enough then to increase it to 11 and further increase it whenever needed?

**Comment by StelianMorariu** [comment]
Of course, we could go with the minimum required.

**Comment by L-Henke** [comment]
We only have 1,21% users with 2.3.3-2.3.7, but why lock out more than necessary.

**Comment by StelianMorariu** [comment]
Well, api 12 & 13 refer to Honeycomb (which, if you remember, was available only for tablets) and 14  is the very first Ice Cream Sandwich (4.0.0)which got upgraded really quick to  4.03 (api 15).

Also, taking a look at some code from the MainActivity, the method to get the back stack entry name was only added in api 14.

I'll create a PR so you can take a look.

**Comment by Graveen** [comment]
Honestly if we go from 10 to 11 let's directly target API 15 (ICS). At least it'll clearly show what target is aimed.

I can't believe devices running less than API15 are able to decrypt a single image with 512Mb RAM :) <jk, i have not tested>

**Comment by L-Henke** [comment]
closed by #116
