### ISSUE TITLE
Recover Vault Password Feature

### ISSUE THREAD

**Issue by StelianMorariu** [SecrecySupportTeam/secrecy#122]
I was checking out the app page from the Google Play Store and I saw that there are many users complaining that they forgot their password. 

One possible solution would be to send the user an email with the vault name and password.

**Comment by L-Henke** [comment]
What? The files are encrypted with the password. There is no possible way to recover a password without breaking the encryption. Only solution would be to make it more clear to the users, that if they lose their password, they will lose their data forever.

**Comment by StelianMorariu** [comment]
I think there was a misunderstanding here, 

One possible solution would be to send the user an email with the vault name and password **when they first create a vault**.

**Comment by L-Henke** [comment]
Also not acceptable, because first we don't have and want the Internet permission and we would send their secret encryption password **unencrypted** around the world. If people want to encrypt files, they have to know that once the password is lost, only a brute force on the password can get their files back...

**Comment by StelianMorariu** [comment]
Valid points.

**Comment by Graveen** [comment]
Agree. Let's not focus on the way user manage his personal datas, because any helpers/workaround will only weaken the process (and generally solves nothing because most of the moaners won't fill an email / also lost their accounts / etc).
I agree with an explicit BIG warning, and so on :)

**Comment by L-Henke** [comment]
@StelianMorariu nevertheless, thanks for the ideas. All input is useful. :+1:
