### ISSUE TITLE
Remove Secrecy_fDroid repo?

### ISSUE THREAD

**Issue by L-Henke** [SecrecySupportTeam/secrecy#86]
Since we removed Crashlytics from the main repo, shouldn't we get rid or the Secrecy_fDroid
repo, since this has just been a version without Crashlytics? We could also push a new version to F-Droid.

**Comment by Graveen** [comment]
Excellent idea !

**Comment by Doplgangr** [comment]
On it. I'll put the repo to depreciation.

**Comment by Doplgangr** [comment]
Done.
Ref:
https://github.com/SecrecySupportTeam/Secrecy_fDroid_DEPRECIATED
