### ISSUE TITLE
Any possibility to answer comments on Google Play

### ISSUE THREAD

**Issue by L-Henke** [SecrecySupportTeam/secrecy#91]
Hey @Doplgangr, is there any way that other people than you are able to answer to comments on Google Play? There are often German comments with issues, which I would like to answer.

**Comment by matthewkwan** [comment]
I think it is possible to add collaborators to maintain the account. I'll check and get back to you.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: L-HenkeSent: Monday, 16 February, 2015 6:39 AMTo: SecrecySupportTeam/secrecyReply To: SecrecySupportTeam/secrecySubject: [secrecy] Any possibility to answer comments on Google Play (#91)Hey @Doplgangr, is there any way that other people than you are able to answer to comments on Google Play? There are often German comments with issues, which I would like to answer.

—Reply to this email directly or view it on GitHub.

**Comment by Doplgangr** [comment]
I have invited you as a collaborator on google play. You can do a various
of actions including replying to comments.

**Comment by L-Henke** [comment]
Thank you very much! Very useful! I can see some error reports with NullPointerExceptions. They occure when non-media files without thumbnails are deleted. That issue has been solved with https://github.com/SecrecySupportTeam/secrecy/commit/ebd55f7a54e9d42a66a113de229f672aa807e418. Maybe we should push a minor update soon.

**Comment by L-Henke** [comment]
@Doplgangr I can only answer in your name unless I create a own developer account...

**Comment by Doplgangr** [comment]
Yah that might be troublesome. You can actually append your signature if you like. It also makes the users easier to get back to you.

**Comment by L-Henke** [comment]
Maybe I'll just create a developer account. Might become handy anyway.
